### ISSUE TITLE
POC: PLUTO+

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/db-template-repo#2]
## goals
- create new repo to produce data product
- output version for OSE and Lynn review and feedback

## tasks to get output
- [ ] Load in source data: mapPLUTO and [7 zoning files](https://github.com/NYCPlanning/db-pluto/blob/960f19857580e5fd4613c7ae442aa429cd55cd12/pluto_build/01_dataloading.sh#L41)
**Build**
- [ ] Decide approach for assigning zoning information - update output table as we go or create intermediary table (i.e. `_pluto`) or?
- [ ] Do we need to update `zoning_create_priority.sql`?  If so, how to we maintain this moving forward?
- [ ] Adapt [10 zoning scripts](https://github.com/NYCPlanning/db-pluto/blob/960f19857580e5fd4613c7ae442aa429cd55cd12/pluto_build/02_build.sh#L68) to new data product.  These can be split out into individual tasks.
- [ ] Determine what other fields depend on zoning district fields.  Currently known: [FAR](https://github.com/NYCPlanning/db-pluto/blob/main/pluto_build/sql/far.sql) 
- [ ] Adapt scripts to update values dependent on Zoning fields, such as FAR fields
- [ ] Assign updated [versioning](https://github.com/NYCPlanning/db-pluto/blob/960f19857580e5fd4613c7ae442aa429cd55cd12/pluto_build/02_build.sh#L105) information with new versioning schema (i.e. 22v3.1)
**QAQC**
- [ ] Determine if we want PLUTO intermediary versions to flow into [QAQC app](https://edm-data-engineering.nycplanningdigital.com/?page=Home) or not
- [ ] If so, build process to incorporate new dataset.  The app should have reports for all the things we we need to check.
- [ ] If not, develop script(s) to confirm nothing but values in expected fields have changed and all else (number of records, etc) has stayed constant compared to source PLUTO.
- [ ] Brainstorm how to QAQC Zoning Tax Lot Database (ZTLDB) and PLUTO+ in one go since both data products will be created by the GIS team monthly and both have most of the same source data.
**Export**
- [ ] Output same [series of files](https://github.com/NYCPlanning/db-pluto#main-files) available for PLUTO, which included additional resources, being mindful of Esri formats and schema.  This probably gets broken out into more discrete tasks.

## notes
- prioritizing making build process work locally, CI run is a stretch goal
